# Comprehensive Skill Ontology - All 302 Skills
# Generated from test dataset with 302 unique skills

CANONICAL_SKILLS = {
    '3d_modeling': '3D Modeling',
    'a_b_testing': 'A/B Testing',
    'acid_transactions': 'ACID Transactions',
    'api_gateway': 'API Gateway',
    'api_testing': 'API Testing',
    'asp_net_core': 'ASP.NET Core',
    'aws': 'AWS',
    'aws_ec2': 'AWS EC2',
    'aws_lambda': 'AWS Lambda',
    'aws_rds': 'AWS RDS',
    'aws_s3': 'AWS S3',
    'agile': 'Agile',
    'android_development': 'Android Development',
    'angular': 'Angular',
    'animation': 'Animation',
    'ansible': 'Ansible',
    'apache_airflow': 'Apache Airflow',
    'apache_kafka': 'Apache Kafka',
    'apache_spark': 'Apache Spark',
    'app_store_optimization': 'App Store Optimization',
    'application_security': 'Application Security',
    'arduino': 'Arduino',
    'argocd': 'ArgoCD',
    'audio_processing': 'Audio Processing',
    'automation': 'Automation',
    'azure': 'Azure',
    'azure_devops': 'Azure DevOps',
    'azure_functions': 'Azure Functions',
    'bdd': 'BDD',
    'bert': 'BERT',
    'backbone_js': 'Backbone.js',
    'big_data': 'Big Data',
    'bitcoin': 'Bitcoin',
    'blender': 'Blender',
    'blockchain': 'Blockchain',
    'bootstrap': 'Bootstrap',
    'csharp': 'C#',
    'cplusplus': 'C++',
    'cplusplus_game_development': 'C++ Game Development',
    'cad': 'CAD',
    'ci_cd': 'CI/CD',
    'cnn': 'CNN',
    'css3': 'CSS3',
    'cassandra': 'Cassandra',
    'chef': 'Chef',
    'circleci': 'CircleCI',
    'client_relations': 'Client Relations',
    'clojure': 'Clojure',
    'cloud_cdn': 'Cloud CDN',
    'cloud_iam': 'Cloud IAM',
    'cloud_monitoring': 'Cloud Monitoring',
    'cloud_storage': 'Cloud Storage',
    'code_review': 'Code Review',
    'communication': 'Communication',
    'compliance': 'Compliance',
    'computer_vision': 'Computer Vision',
    'consensus_algorithms': 'Consensus Algorithms',
    'couchdb': 'CouchDB',
    'critical_thinking': 'Critical Thinking',
    'cross_browser_compatibility': 'Cross-browser Compatibility',
    'cryptocurrency': 'Cryptocurrency',
    'cryptography': 'Cryptography',
    'cybersecurity': 'Cybersecurity',
    'cypress': 'Cypress',
    'dart': 'Dart',
    'data_analysis': 'Data Analysis',
    'data_cleaning': 'Data Cleaning',
    'data_mining': 'Data Mining',
    'data_modeling': 'Data Modeling',
    'data_visualization': 'Data Visualization',
    'data_warehousing': 'Data Warehousing',
    'database_design': 'Database Design',
    'datadog': 'Datadog',
    'defi': 'DeFi',
    'deep_learning': 'Deep Learning',
    'distributed_ledger': 'Distributed Ledger',
    'django': 'Django',
    'docker': 'Docker',
    'dynamodb': 'DynamoDB',
    'elk_stack': 'ELK Stack',
    'etl': 'ETL',
    'edge_computing': 'Edge Computing',
    'elasticsearch': 'Elasticsearch',
    'elixir': 'Elixir',
    'embedded_systems': 'Embedded Systems',
    'ember_js': 'Ember.js',
    'encryption': 'Encryption',
    'end_to_end_testing': 'End-to-End Testing',
    'ethereum': 'Ethereum',
    'express_js': 'Express.js',
    'fsharp': 'F#',
    'fastapi': 'FastAPI',
    'feature_engineering': 'Feature Engineering',
    'firebase': 'Firebase',
    'firewalls': 'Firewalls',
    'flask': 'Flask',
    'flutter': 'Flutter',
    'gan': 'GAN',
    'gdpr': 'GDPR',
    'gis': 'GIS',
    'gpt': 'GPT',
    'game_ai': 'Game AI',
    'game_design': 'Game Design',
    'gatsby': 'Gatsby',
    'github_actions': 'GitHub Actions',
    'gitlab_ci': 'GitLab CI',
    'go': 'Go',
    'google_cloud_platform': 'Google Cloud Platform',
    'google_kubernetes_engine': 'Google Kubernetes Engine',
    'grafana': 'Grafana',
    'graphql': 'GraphQL',
    'groovy': 'Groovy',
    'hls': 'HLS',
    'html5': 'HTML5',
    'hadoop': 'Hadoop',
    'haskell': 'Haskell',
    'helm': 'Helm',
    'hyperledger': 'Hyperledger',
    'hyperparameter_tuning': 'Hyperparameter Tuning',
    'hypothesis_testing': 'Hypothesis Testing',
    'ibm_cloud': 'IBM Cloud',
    'iso_27001': 'ISO 27001',
    'image_classification': 'Image Classification',
    'image_processing': 'Image Processing',
    'in_app_purchases': 'In-App Purchases',
    'incident_response': 'Incident Response',
    'indexing': 'Indexing',
    'influxdb': 'InfluxDB',
    'infrastructure_as_code': 'Infrastructure as Code',
    'integration_testing': 'Integration Testing',
    'iot': 'IoT',
    'ionic': 'Ionic',
    'jmeter': 'JMeter',
    'junit': 'JUnit',
    'jwt': 'JWT',
    'java': 'Java',
    'javascript': 'JavaScript',
    'jenkins': 'Jenkins',
    'jest': 'Jest',
    'jetpack_compose': 'Jetpack Compose',
    'julia': 'Julia',
    'jupyter': 'Jupyter',
    'kanban': 'Kanban',
    'keras': 'Keras',
    'kotlin': 'Kotlin',
    'kubernetes': 'Kubernetes',
    'less': 'LESS',
    'lstm': 'LSTM',
    'laravel': 'Laravel',
    'leadership': 'Leadership',
    'lightgbm': 'LightGBM',
    'load_testing': 'Load Testing',
    'location_services': 'Location Services',
    'lua': 'Lua',
    'matlab': 'MATLAB',
    'mlops': 'MLOps',
    'machine_learning': 'Machine Learning',
    'mariadb': 'MariaDB',
    'material_ui': 'Material-UI',
    'matplotlib': 'Matplotlib',
    'maya': 'Maya',
    'mentoring': 'Mentoring',
    'microcontrollers': 'Microcontrollers',
    'microservices': 'Microservices',
    'mobx': 'MobX',
    'mobile_security': 'Mobile Security',
    'mobile_ui_ux': 'Mobile UI/UX',
    'mocha': 'Mocha',
    'model_deployment': 'Model Deployment',
    'mongodb': 'MongoDB',
    'multiplayer_networking': 'Multiplayer Networking',
    'mysql': 'MySQL',
    'nft': 'NFT',
    'natural_language_processing': 'Natural Language Processing',
    'neo4j': 'Neo4j',
    'nestjs': 'NestJS',
    'network_security': 'Network Security',
    'neural_networks': 'Neural Networks',
    'new_relic': 'New Relic',
    'next_js': 'Next.js',
    'nosql': 'NoSQL',
    'node_js': 'Node.js',
    'numpy': 'NumPy',
    'nuxt_js': 'Nuxt.js',
    'oauth': 'OAuth',
    'owasp': 'OWASP',
    'object_detection': 'Object Detection',
    'objective_c': 'Objective-C',
    'offline_storage': 'Offline Storage',
    'oracle': 'Oracle',
    'oracle_cloud': 'Oracle Cloud',
    'php': 'PHP',
    'pwa': 'PWA',
    'pandas': 'Pandas',
    'penetration_testing': 'Penetration Testing',
    'performance_testing': 'Performance Testing',
    'perl': 'Perl',
    'phoenix': 'Phoenix',
    'physics_engine': 'Physics Engine',
    'plotly': 'Plotly',
    'postgresql': 'PostgreSQL',
    'postman': 'Postman',
    'power_bi': 'Power BI',
    'powershell': 'PowerShell',
    'predictive_analytics': 'Predictive Analytics',
    'presentation_skills': 'Presentation Skills',
    'problem_solving': 'Problem Solving',
    'project_management': 'Project Management',
    'prometheus': 'Prometheus',
    'puppet': 'Puppet',
    'push_notifications': 'Push Notifications',
    'pytorch': 'PyTorch',
    'pytest': 'Pytest',
    'python': 'Python',
    'quantum_computing': 'Quantum Computing',
    'query_optimization': 'Query Optimization',
    'r': 'R',
    'rest_api': 'REST API',
    'rnn': 'RNN',
    'rtmp': 'RTMP',
    'rtos': 'RTOS',
    'raspberry_pi': 'Raspberry Pi',
    'react': 'React',
    'react_native': 'React Native',
    'redis': 'Redis',
    'redux': 'Redux',
    'reinforcement_learning': 'Reinforcement Learning',
    'replication': 'Replication',
    'responsive_design': 'Responsive Design',
    'risk_assessment': 'Risk Assessment',
    'robotics': 'Robotics',
    'ruby': 'Ruby',
    'ruby_on_rails': 'Ruby on Rails',
    'rust': 'Rust',
    'siem': 'SIEM',
    'soc_2': 'SOC 2',
    'sql_server': 'SQL Server',
    'sqlite': 'SQLite',
    'ssl_tls': 'SSL/TLS',
    'sass': 'Sass',
    'scala': 'Scala',
    'scrum': 'Scrum',
    'seaborn': 'Seaborn',
    'security_auditing': 'Security Auditing',
    'security_testing': 'Security Testing',
    'selenium': 'Selenium',
    'serverless': 'Serverless',
    'serverless_framework': 'Serverless Framework',
    'session_management': 'Session Management',
    'sharding': 'Sharding',
    'shell_scripting': 'Shell Scripting',
    'signal_processing': 'Signal Processing',
    'smart_contracts': 'Smart Contracts',
    'solidity': 'Solidity',
    'splunk': 'Splunk',
    'spring_boot': 'Spring Boot',
    'stakeholder_management': 'Stakeholder Management',
    'statistical_analysis': 'Statistical Analysis',
    'statistical_modeling': 'Statistical Modeling',
    'streaming_technologies': 'Streaming Technologies',
    'supabase': 'Supabase',
    'svelte': 'Svelte',
    'swift': 'Swift',
    'swiftui': 'SwiftUI',
    'tableau': 'Tableau',
    'tailwind_css': 'Tailwind CSS',
    'team_collaboration': 'Team Collaboration',
    'technical_writing': 'Technical Writing',
    'tensorflow': 'TensorFlow',
    'terraform': 'Terraform',
    'test_automation': 'Test Automation',
    'test_driven_development': 'Test-Driven Development',
    'testng': 'TestNG',
    'threat_modeling': 'Threat Modeling',
    'time_management': 'Time Management',
    'time_series_analysis': 'Time Series Analysis',
    'timescaledb': 'TimescaleDB',
    'token_economics': 'Token Economics',
    'transformer_models': 'Transformer Models',
    'travis_ci': 'Travis CI',
    'typescript': 'TypeScript',
    'unit_testing': 'Unit Testing',
    'unity': 'Unity',
    'unreal_engine': 'Unreal Engine',
    'vba': 'VBA',
    'vr_ar_development': 'VR/AR Development',
    'vagrant': 'Vagrant',
    'video_processing': 'Video Processing',
    'vite': 'Vite',
    'vue_js': 'Vue.js',
    'vulnerability_assessment': 'Vulnerability Assessment',
    'web_components': 'Web Components',
    'web3_js': 'Web3.js',
    'webrtc': 'WebRTC',
    'websockets': 'WebSockets',
    'webpack': 'Webpack',
    'xgboost': 'XGBoost',
    'xamarin': 'Xamarin',
    'grpc': 'gRPC',
    'ios_development': 'iOS Development',
    'jquery': 'jQuery',
    'scikit_learn': 'scikit-learn',
}

REFERENCE_SKILLS = list(CANONICAL_SKILLS.values())
